# Generated by Django 3.1.3 on 2021-02-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lkpFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='lkpPing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='lkpResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('imgLink', models.CharField(blank=True, max_length=250, null=True)),
                ('lastCheck', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(max_length=500)),
                ('frequency', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('desiredResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_desired_result', to='monitor.lkpresult')),
                ('frequencyType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.lkpfrequency')),
                ('lastResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_last_result', to='monitor.lkpresult')),
                ('ping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.lkpping')),
            ],
        ),
    ]
