# Generated by Django 3.1.3 on 2021-02-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='resultValue',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
    ]
