# Generated by Django 3.1.3 on 2021-02-05 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_sites_resultvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='lastResult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_last_result', to='monitor.lkpresult'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='resultValue',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
