# Generated by Django 3.1.3 on 2021-02-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20210205_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='imgLink',
        ),
    ]
